import type { AuditReport } from "./resport-schema";

const CATEGORY_TITLES: Record<string, string> = {
  seo: "Technical SEO",
  accessibility: "Accessibility",
  performance: "Performance",
  security: "Security Headers",
  html: "HTML Structure",
};

const SEVERITY_BADGES: Record<string, string> = {
  critical: "🔴 CRITICAL",
  high: "🟠 HIGH",
  medium: "🟡 MEDIUM",
  low: "🔵 LOW",
  info: "⚪ INFO",
};

export function auditReportToMarkdown(report: AuditReport): string {
  const lines: string[] = [];
  const push = (...parts: string[]) => lines.push(...parts);

  push(
    `# SiteSage AI — Website Audit Report`,
    ``,
    `| | |`,
    `|---|---|`,
    `| **Audited URL** | ${report.auditedUrl} |`,
    `| **Final URL** | ${report.finalUrl} |`,
    `| **Generated** | ${report.generatedAt} |`,
    `| **Overall score** | ${report.overallScore === null ? "n/a" : `${report.overallScore}/100`} |`,
    `| **Mode** | ${report.mode}${report.demoMode ? " (Demo Mode — canned snapshot, scripted synthesis)" : ""} |`,
    ``,
    `> ${report.disclaimer}`,
    ``,
    `## Summary`,
    ``,
    report.summary,
    ``,
    `## Category Scores`,
    ``,
    `| Category | Score | Summary |`,
    `|---|---|---|`,
  );

  for (const c of report.categoryScores) {
    const score = c.evaluated && c.score !== null ? `${c.score}/100` : "n/a";
    push(
      `| ${CATEGORY_TITLES[c.category] ?? c.category} | ${score} | ${c.summary.replace(/\|/g, "\\|")} |`,
    );
  }

  push(``, `## Findings`, ``);

  if (report.findings.length === 0) {
    push(`No findings were recorded.`);
  }
  for (const category of Object.keys(CATEGORY_TITLES)) {
    const inCategory = report.findings.filter((f) => f.category === category);
    if (inCategory.length === 0) continue;
    push(`### ${CATEGORY_TITLES[category]}`, ``);
    for (const f of inCategory) {
      push(
        `#### ${SEVERITY_BADGES[f.severity]} — ${f.title}`,
        ``,
        f.description,
        ``,
        `- **Evidence:** ${f.evidence || "n/a"}`,
        `- **Confidence:** ${Math.round(f.confidence * 100)}%`,
        f.affectedElements.length > 0
          ? `- **Affected:** ${f.affectedElements.map((e) => `\`${e}\``).join(", ")}`
          : `- **Affected:** n/a`,
        ``,
        `**Recommendation:** ${f.recommendation}`,
        ``,
      );
      if (f.codeExample) {
        push("```tsx", f.codeExample, "```", ``);
      }
    }
  }

  push(`## Prioritized Action Plan`, ``);
  for (const a of report.prioritizedActionPlan) {
    push(
      `### ${a.priority}. ${a.title} — impact: ${a.impact}, effort: ${a.effort}`,
    );
    for (const [i, step] of a.steps.entries()) {
      push(`${i + 1}. ${step}`);
    }
    push(``);
  }

  push(`## Positive Observations`, ``);
  for (const p of report.positiveObservations) push(`- ${p}`);
  push(``, `## Limitations`, ``);
  for (const l of report.limitations) push(`- ${l}`);

  push(
    ``,
    `---`,
    `*Generated by SiteSage AI. ${report.demoMode ? "Demo Mode: no live AI request was made." : `Model: ${report.model}.`}*`,
  );

  return lines.join("\n");
}
