import { load } from "cheerio";

export interface ImageEvidence {
  src: string;
  alt: string | null;
  issue:
    | "missing_alt"
    | "empty_alt_needs_review"
    | "suspicious_filename"
    | "missing_dimensions";
  detail: string;
}

export interface ImagesAnalysis {
  total: number;
  missingAlt: number;
  emptyAlt: number;
  decorativeEmptyAlt: number;
  needsReviewEmptyAlt: number;
  suspiciousFilenames: number;
  lazyLoaded: number;
  withWidthHeight: number;
  widthHeightCoveragePct: number;
  evidence: ImageEvidence[];
}

const SUSPICIOUS_FILENAME =
  /(^|\/)(img[-_]?\d+|image[-_]?\d+|dsc[-_]?\d+|pxl[-_]?\d+|screenshot[-_ ]?\d*|screen ?shot|untitled[-_ ]?\d*|whatsapp image|\d{6,}[^/]*\.(?:jpe?g|png|gif|webp))/i;

const MAX_EVIDENCE = 8;
const MAX_IMAGES_SCANNED = 400;

function resolveSrc(src: string, baseUrl: string): string {
  try {
    return new URL(src, baseUrl).toString();
  } catch {
    return src;
  }
}

export function inspectImages(html: string, baseUrl: string): ImagesAnalysis {
  const $ = load(html);

  let total = 0;
  let missingAlt = 0;
  let emptyAlt = 0;
  let decorativeEmptyAlt = 0;
  let needsReviewEmptyAlt = 0;
  let suspiciousFilenames = 0;
  let lazyLoaded = 0;
  let withWidthHeight = 0;
  const evidence: ImageEvidence[] = [];

  $("img").each((_, el) => {
    if (total >= MAX_IMAGES_SCANNED) return false;
    total += 1;

    const img = $(el);
    const rawSrc = img.attr("src") ?? img.attr("data-src") ?? "";
    const src = rawSrc.startsWith("data:")
      ? "data:image/…(inline)"
      : resolveSrc(rawSrc, baseUrl);

    const altAttr = img.attr("alt");

    const isDecorative =
      img.attr("role") === "presentation" ||
      img.attr("role") === "none" ||
      img.attr("aria-hidden") === "true";

    if (altAttr === undefined) {
      missingAlt += 1;
      if (evidence.length < MAX_EVIDENCE) {
        evidence.push({
          src,
          alt: null,
          issue: "missing_alt",
          detail:
            "The alt attribute is missing entirely; assistive tech may read the filename aloud.",
        });
      }
    } else if (altAttr.trim() === "") {
      emptyAlt += 1;
      if (isDecorative) {
        decorativeEmptyAlt += 1;
      } else {
        needsReviewEmptyAlt += 1;
        if (evidence.length < MAX_EVIDENCE) {
          evidence.push({
            src,
            alt: "",
            issue: "empty_alt_needs_review",
            detail:
              "Empty alt on a non-decorative-looking image — confirm it is truly decorative.",
          });
        }
      }
    }

    if (rawSrc && !rawSrc.startsWith("data:")) {
      const filename = rawSrc.split("?")[0] ?? rawSrc;

      if (SUSPICIOUS_FILENAME.test(filename)) {
        suspiciousFilenames += 1;
        if (evidence.length < MAX_EVIDENCE) {
          evidence.push({
            src,
            alt: altAttr ?? null,
            issue: "suspicious_filename",
            detail:
              "Autogenerated-looking filename; also hurts image SEO when alt is weak.",
          });
        }
      }
    }

    if (img.attr("loading") === "lazy") {
      lazyLoaded += 1;
      if (img.attr("width") !== undefined && img.attr("height") !== undefined) {
        withWidthHeight += 1;
      }
    }

    return true;
  });
  return {
    total,
    missingAlt,
    emptyAlt,
    decorativeEmptyAlt,
    needsReviewEmptyAlt,
    suspiciousFilenames,
    lazyLoaded,
    withWidthHeight,
    widthHeightCoveragePct:
      total === 0 ? 100 : Math.round((withWidthHeight / total) * 100),
    evidence,
  };
}
